name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - features

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  # Set GitHub secrets:
  # VERCEL_TOKEN      - from https://vercel.com/account/tokens
  # VERCEL_ORG_ID     - team_AZhsySUU2ACMCFATO6VpBxVU
  # VERCEL_PROJECT_ID - prj_bGzsreBd9cK71CeIn6ohVC1JSXDU

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=${{ github.ref_name == 'main' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: vercel build --yes --token=${{ secrets.VERCEL_TOKEN }} ${{ github.ref_name == 'main' && '--prod' || '' }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --yes --token=${{ secrets.VERCEL_TOKEN }} ${{ github.ref_name == 'main' && '--prod' || '' }}
